# Default values for invoice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.digitalocean.com
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev-0.0.17"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  
gateway:
  selector:
    - api-gateway.istio-system.svc.cluster.local
  #- api-gateway
  hosts:
    -invoice.com
services: 
  organization:
    address: "http://organization.svc.cluster.local"
    port: "80"
  customer:
    address: "http://customer.svc.cluster.local"
    port: "80"      
  admin:
    address: "http://admin.svc.cluster.local"
    port: "80"
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits: {}
   # cpu: 100m
    #memory: 128Mi
 # requests:
   # cpu: 100m
  #  memory: 128Mi
  
  # POSTGRESQL PROPERTIES
postgres:
  port: 5432
  databaseName: "invoice"
  keyspace: "postgresql"
  userName: "testadmin"
  password: "test"
  contact-points: "postgresql-dev.postgresql.svc.cluster.local"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
   #targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
